from __future__ import annotations

import importlib

OPERATION_TO_RESOURCE: dict[str, str] = {
    'drafts_create': 'drafts',
    'drafts_delete': 'drafts',
    'drafts_get': 'drafts',
    'drafts_list': 'drafts',
    'drafts_send': 'drafts',
    'drafts_update': 'drafts',
    'get_profile': 'root',
    'history_list': 'history',
    'labels_create': 'labels',
    'labels_delete': 'labels',
    'labels_get': 'labels',
    'labels_list': 'labels',
    'labels_patch': 'labels',
    'labels_update': 'labels',
    'messages_attachments_get': 'messages_attachments',
    'messages_batch_delete': 'messages',
    'messages_batch_modify': 'messages',
    'messages_delete': 'messages',
    'messages_get': 'messages',
    'messages_import': 'messages',
    'messages_insert': 'messages',
    'messages_list': 'messages',
    'messages_modify': 'messages',
    'messages_send': 'messages',
    'messages_trash': 'messages',
    'messages_untrash': 'messages',
    'settings_cse_identities_create': 'settings_cse_identities',
    'settings_cse_identities_delete': 'settings_cse_identities',
    'settings_cse_identities_get': 'settings_cse_identities',
    'settings_cse_identities_list': 'settings_cse_identities',
    'settings_cse_identities_patch': 'settings_cse_identities',
    'settings_cse_keypairs_create': 'settings_cse_keypairs',
    'settings_cse_keypairs_disable': 'settings_cse_keypairs',
    'settings_cse_keypairs_enable': 'settings_cse_keypairs',
    'settings_cse_keypairs_get': 'settings_cse_keypairs',
    'settings_cse_keypairs_list': 'settings_cse_keypairs',
    'settings_cse_keypairs_obliterate': 'settings_cse_keypairs',
    'settings_delegates_create': 'settings_delegates',
    'settings_delegates_delete': 'settings_delegates',
    'settings_delegates_get': 'settings_delegates',
    'settings_delegates_list': 'settings_delegates',
    'settings_filters_create': 'settings_filters',
    'settings_filters_delete': 'settings_filters',
    'settings_filters_get': 'settings_filters',
    'settings_filters_list': 'settings_filters',
    'settings_forwarding_addresses_create': 'settings_forwarding_addresses',
    'settings_forwarding_addresses_delete': 'settings_forwarding_addresses',
    'settings_forwarding_addresses_get': 'settings_forwarding_addresses',
    'settings_forwarding_addresses_list': 'settings_forwarding_addresses',
    'settings_get_auto_forwarding': 'settings',
    'settings_get_imap': 'settings',
    'settings_get_language': 'settings',
    'settings_get_pop': 'settings',
    'settings_get_vacation': 'settings',
    'settings_send_as_create': 'settings_send_as',
    'settings_send_as_delete': 'settings_send_as',
    'settings_send_as_get': 'settings_send_as',
    'settings_send_as_list': 'settings_send_as',
    'settings_send_as_patch': 'settings_send_as',
    'settings_send_as_smime_info_delete': 'settings_send_as_smime_info',
    'settings_send_as_smime_info_get': 'settings_send_as_smime_info',
    'settings_send_as_smime_info_insert': 'settings_send_as_smime_info',
    'settings_send_as_smime_info_list': 'settings_send_as_smime_info',
    'settings_send_as_smime_info_set_default': 'settings_send_as_smime_info',
    'settings_send_as_update': 'settings_send_as',
    'settings_send_as_verify': 'settings_send_as',
    'settings_update_auto_forwarding': 'settings',
    'settings_update_imap': 'settings',
    'settings_update_language': 'settings',
    'settings_update_pop': 'settings',
    'settings_update_vacation': 'settings',
    'stop': 'root',
    'threads_delete': 'threads',
    'threads_get': 'threads',
    'threads_list': 'threads',
    'threads_modify': 'threads',
    'threads_trash': 'threads',
    'threads_untrash': 'threads',
    'watch': 'root',
}

RESOURCE_REGISTRY: dict[str, tuple[str, str]] = {
    'drafts': ('lemma_connectors.gmail.resources.drafts', 'GmailDraftsResource'),
    'history': ('lemma_connectors.gmail.resources.history', 'GmailHistoryResource'),
    'labels': ('lemma_connectors.gmail.resources.labels', 'GmailLabelsResource'),
    'messages': ('lemma_connectors.gmail.resources.messages', 'GmailMessagesResource'),
    'messages_attachments': ('lemma_connectors.gmail.resources.messages_attachments', 'GmailMessagesAttachmentsResource'),
    'root': ('lemma_connectors.gmail.resources.root', 'GmailRootResource'),
    'settings': ('lemma_connectors.gmail.resources.settings', 'GmailSettingsResource'),
    'settings_cse_identities': ('lemma_connectors.gmail.resources.settings_cse_identities', 'GmailSettingsCseIdentitiesResource'),
    'settings_cse_keypairs': ('lemma_connectors.gmail.resources.settings_cse_keypairs', 'GmailSettingsCseKeypairsResource'),
    'settings_delegates': ('lemma_connectors.gmail.resources.settings_delegates', 'GmailSettingsDelegatesResource'),
    'settings_filters': ('lemma_connectors.gmail.resources.settings_filters', 'GmailSettingsFiltersResource'),
    'settings_forwarding_addresses': ('lemma_connectors.gmail.resources.settings_forwarding_addresses', 'GmailSettingsForwardingAddressesResource'),
    'settings_send_as': ('lemma_connectors.gmail.resources.settings_send_as', 'GmailSettingsSendAsResource'),
    'settings_send_as_smime_info': ('lemma_connectors.gmail.resources.settings_send_as_smime_info', 'GmailSettingsSendAsSmimeInfoResource'),
    'threads': ('lemma_connectors.gmail.resources.threads', 'GmailThreadsResource'),
}


def build_resource(client, resource_slug: str):
    """Lazily import and build a single resource client by slug."""
    module_path, class_name = RESOURCE_REGISTRY[resource_slug]
    module = importlib.import_module(module_path)
    return getattr(module, class_name)(client)


def build_resources(client):
    """Eagerly build all resource clients (backward-compatible)."""
    return {slug: build_resource(client, slug) for slug in RESOURCE_REGISTRY}
