from __future__ import annotations

import importlib

OPERATION_TO_RESOURCE: dict[str, str] = {
    'add_actor_users': 'actor_users',
    'add_attachment': 'attachment',
    'add_comment': 'comment',
    'add_field_to_default_screen': 'field_to_default_screen',
    'add_gadget': 'gadget',
    'add_issue_types_to_context': 'issue_types_to_context',
    'add_issue_types_to_issue_type_scheme': 'issue_types_to_issue_type_scheme',
    'add_notifications': 'notifications',
    'add_project_role_actors_to_role': 'project_role_actors_to_role',
    'add_screen_tab': 'screen_tab',
    'add_screen_tab_field': 'screen_tab_field',
    'add_share_permission': 'share_permission',
    'add_user_to_group': 'user_to_group',
    'add_vote': 'vote',
    'add_watcher': 'watcher',
    'add_worklog': 'worklog',
    'addon_properties_resource_delete_addon_property_delete': 'addon_properties_resource',
    'addon_properties_resource_get_addon_properties_get': 'addon_properties_resource',
    'addon_properties_resource_get_addon_property_get': 'addon_properties_resource',
    'addon_properties_resource_put_addon_property_put': 'addon_properties_resource',
    'analyse_expression': 'analyse',
    'app_issue_field_value_update_resource_update_issue_fields_put': 'app_issue_field_value_update_resource',
    'append_mappings_for_issue_type_screen_scheme': 'mappings_for_issue_type_screen_scheme',
    'archive_project': 'project',
    'assign_field_configuration_scheme_to_project': 'assign_field_configuration_scheme_to',
    'assign_issue': 'assign',
    'assign_issue_type_scheme_to_project': 'assign_issue_type_scheme_to',
    'assign_issue_type_screen_scheme_to_project': 'assign_issue_type_screen_scheme_to',
    'assign_permission_scheme': 'assign_permission',
    'assign_projects_to_custom_field_context': 'assign_projects_to_custom_field',
    'assign_scheme_to_project': 'assign_scheme_to',
    'bulk_delete_issue_property': 'bulk_delete_issue',
    'bulk_get_groups': 'bulk_get',
    'bulk_get_users': 'bulk_get',
    'bulk_get_users_migration': 'bulk_get_users',
    'bulk_set_issue_properties_by_issue': 'bulk_set_issue_properties_by',
    'bulk_set_issue_property': 'bulk_set_issue',
    'bulk_set_issues_properties_list': 'bulk_set_issues_properties',
    'cancel_task': 'cancel',
    'change_filter_owner': 'change_filter',
    'copy_dashboard': 'dashboard',
    'create_component': 'component',
    'create_custom_field': 'custom_field',
    'create_custom_field_context': 'custom_field_context',
    'create_custom_field_option': 'custom_field_option',
    'create_dashboard': 'dashboard',
    'create_field_configuration': 'field_configuration',
    'create_field_configuration_scheme': 'field_configuration_scheme',
    'create_filter': 'filter',
    'create_group': 'group',
    'create_issue': 'issue',
    'create_issue_field_option': 'issue_field_option',
    'create_issue_link_type': 'issue_link_type',
    'create_issue_type': 'issue_type',
    'create_issue_type_avatar': 'issue_type_avatar',
    'create_issue_type_scheme': 'issue_type_scheme',
    'create_issue_type_screen_scheme': 'issue_type_screen_scheme',
    'create_issues': 'issues',
    'create_notification_scheme': 'notification_scheme',
    'create_or_update_remote_issue_link': 'or_update_remote_issue_link',
    'create_permission_grant': 'permission_grant',
    'create_permission_scheme': 'permission_scheme',
    'create_priority': 'priority',
    'create_project': 'project',
    'create_project_avatar': 'project_avatar',
    'create_project_category': 'project_category',
    'create_project_role': 'project_role',
    'create_resolution': 'resolution',
    'create_screen': 'screen',
    'create_screen_scheme': 'screen_scheme',
    'create_statuses': 'statuses',
    'create_ui_modification': 'ui_modification',
    'create_user': 'user',
    'create_version': 'version',
    'create_workflow': 'workflow',
    'create_workflow_scheme': 'workflow_scheme',
    'create_workflow_scheme_draft_from_parent': 'workflow_scheme_draft_from_parent',
    'create_workflow_transition_property': 'workflow_transition_property',
    'delete_actor': 'actor',
    'delete_and_replace_version': 'and_replace_version',
    'delete_avatar': 'avatar',
    'delete_comment': 'comment',
    'delete_comment_property': 'comment_property',
    'delete_component': 'component',
    'delete_custom_field': 'custom_field',
    'delete_custom_field_context': 'custom_field_context',
    'delete_custom_field_option': 'custom_field_option',
    'delete_dashboard': 'dashboard',
    'delete_dashboard_item_property': 'dashboard_item_property',
    'delete_default_workflow': 'default_workflow',
    'delete_draft_default_workflow': 'draft_default_workflow',
    'delete_draft_workflow_mapping': 'draft_workflow_mapping',
    'delete_favourite_for_filter': 'favourite_for_filter',
    'delete_field_configuration': 'field_configuration',
    'delete_field_configuration_scheme': 'field_configuration_scheme',
    'delete_filter': 'filter',
    'delete_inactive_workflow': 'inactive_workflow',
    'delete_issue': 'issue',
    'delete_issue_field_option': 'issue_field_option',
    'delete_issue_link': 'issue_link',
    'delete_issue_link_type': 'issue_link_type',
    'delete_issue_property': 'issue_property',
    'delete_issue_type': 'issue_type',
    'delete_issue_type_property': 'issue_type_property',
    'delete_issue_type_scheme': 'issue_type_scheme',
    'delete_issue_type_screen_scheme': 'issue_type_screen_scheme',
    'delete_locale': 'locale',
    'delete_notification_scheme': 'notification_scheme',
    'delete_permission_scheme': 'permission_scheme',
    'delete_permission_scheme_entity': 'permission_scheme_entity',
    'delete_priority': 'priority',
    'delete_project': 'project',
    'delete_project_asynchronously': 'project_asynchronously',
    'delete_project_avatar': 'project_avatar',
    'delete_project_property': 'project_property',
    'delete_project_role': 'project_role',
    'delete_project_role_actors_from_role': 'project_role_actors_from_role',
    'delete_remote_issue_link_by_global_id': 'remote_issue_link_by_global_id',
    'delete_remote_issue_link_by_id': 'remote_issue_link_by_id',
    'delete_resolution': 'resolution',
    'delete_screen': 'screen',
    'delete_screen_scheme': 'screen_scheme',
    'delete_screen_tab': 'screen_tab',
    'delete_share_permission': 'share_permission',
    'delete_statuses_by_id': 'statuses_by_id',
    'delete_ui_modification': 'ui_modification',
    'delete_user_property': 'user_property',
    'delete_version': 'version',
    'delete_webhook_by_id': 'webhook_by_id',
    'delete_workflow_mapping': 'workflow_mapping',
    'delete_workflow_scheme': 'workflow_scheme',
    'delete_workflow_scheme_draft': 'workflow_scheme_draft',
    'delete_workflow_scheme_draft_issue_type': 'workflow_scheme_draft_issue_type',
    'delete_workflow_scheme_issue_type': 'workflow_scheme_issue_type',
    'delete_workflow_transition_property': 'workflow_transition_property',
    'delete_workflow_transition_rule_configurations': 'workflow_transition_rule_configurations',
    'delete_worklog': 'worklog',
    'delete_worklog_property': 'worklog_property',
    'do_transition': 'do',
    'dynamic_modules_resource_get_modules_get': 'dynamic_modules_resource',
    'dynamic_modules_resource_register_modules_post': 'dynamic_modules_resource',
    'dynamic_modules_resource_remove_modules_delete': 'dynamic_modules_resource',
    'edit_issue': 'edit',
    'evaluate_jira_expression': 'evaluate_jira',
    'expand_attachment_for_humans': 'attachment_for_humans',
    'expand_attachment_for_machines': 'attachment_for_machines',
    'find_assignable_users': 'find_assignable',
    'find_bulk_assignable_users': 'find_bulk_assignable',
    'find_groups': 'find',
    'find_user_keys_by_query': 'find_user_keys_by',
    'find_users': 'find',
    'find_users_and_groups': 'find_users_and',
    'find_users_by_query': 'find_users_by',
    'find_users_for_picker': 'find_users_for',
    'find_users_with_all_permissions': 'find_users_with_all',
    'find_users_with_browse_permission': 'find_users_with_browse',
    'fully_update_project_role': 'fully_update_project',
    'get_accessible_project_type_by_key': 'accessible_project_type_by_key',
    'get_advanced_settings': 'advanced_settings',
    'get_all_accessible_project_types': 'all_accessible_project_types',
    'get_all_application_roles': 'all_application_roles',
    'get_all_available_dashboard_gadgets': 'all_available_dashboard_gadgets',
    'get_all_dashboards': 'all_dashboards',
    'get_all_field_configuration_schemes': 'all_field_configuration_schemes',
    'get_all_field_configurations': 'all_field_configurations',
    'get_all_gadgets': 'all_gadgets',
    'get_all_issue_field_options': 'all_issue_field_options',
    'get_all_issue_type_schemes': 'all_issue_type_schemes',
    'get_all_labels': 'all_labels',
    'get_all_permission_schemes': 'all_permission_schemes',
    'get_all_permissions': 'all_permissions',
    'get_all_project_avatars': 'all_project_avatars',
    'get_all_project_categories': 'all_project_categories',
    'get_all_project_roles': 'all_project_roles',
    'get_all_project_types': 'all_project_types',
    'get_all_projects': 'all_projects',
    'get_all_screen_tab_fields': 'all_screen_tab_fields',
    'get_all_screen_tabs': 'all_screen_tabs',
    'get_all_statuses': 'all_statuses',
    'get_all_system_avatars': 'all_system_avatars',
    'get_all_users': 'all_users',
    'get_all_users_default': 'all_users_default',
    'get_all_workflow_schemes': 'all_workflow_schemes',
    'get_all_workflows': 'all_workflows',
    'get_alternative_issue_types': 'alternative_issue_types',
    'get_application_property': 'application_property',
    'get_application_role': 'application_role',
    'get_approximate_application_license_count': 'approximate_application_license_count',
    'get_approximate_license_count': 'approximate_license_count',
    'get_assigned_permission_scheme': 'assigned_permission_scheme',
    'get_attachment': 'attachment',
    'get_attachment_content': 'attachment_content',
    'get_attachment_meta': 'attachment_meta',
    'get_attachment_thumbnail': 'attachment_thumbnail',
    'get_audit_records': 'audit_records',
    'get_auto_complete': 'auto_complete',
    'get_auto_complete_post': 'auto_complete_post',
    'get_available_screen_fields': 'available_screen_fields',
    'get_available_time_tracking_implementations': 'available_time_tracking_implementations',
    'get_avatar_image_by_id': 'avatar_image_by_id',
    'get_avatar_image_by_owner': 'avatar_image_by_owner',
    'get_avatar_image_by_type': 'avatar_image_by_type',
    'get_avatars': 'avatars',
    'get_banner': 'banner',
    'get_bulk_permissions': 'bulk_permissions',
    'get_change_logs': 'change_logs',
    'get_change_logs_by_ids': 'change_logs_by_ids',
    'get_columns': 'columns',
    'get_comment': 'comment',
    'get_comment_property': 'comment_property',
    'get_comment_property_keys': 'comment_property_keys',
    'get_comments': 'comments',
    'get_comments_by_ids': 'comments_by_ids',
    'get_component': 'component',
    'get_component_related_issues': 'component_related_issues',
    'get_configuration': 'configuration',
    'get_contexts_for_field': 'contexts_for_field',
    'get_contexts_for_field_deprecated': 'contexts_for_field_deprecated',
    'get_create_issue_meta': 'create_issue_meta',
    'get_current_user': 'current_user',
    'get_custom_field_configuration': 'custom_field_configuration',
    'get_custom_field_contexts_for_projects_and_issue_types': 'custom_field_contexts_for_projects_and_issue_types',
    'get_custom_field_option': 'custom_field_option',
    'get_dashboard': 'dashboard',
    'get_dashboard_item_property': 'dashboard_item_property',
    'get_dashboard_item_property_keys': 'dashboard_item_property_keys',
    'get_dashboards_paginated': 'dashboards_paginated',
    'get_default_share_scope': 'default_share_scope',
    'get_default_values': 'default_values',
    'get_default_workflow': 'default_workflow',
    'get_draft_default_workflow': 'draft_default_workflow',
    'get_draft_workflow': 'draft_workflow',
    'get_dynamic_webhooks_for_app': 'dynamic_webhooks_for_app',
    'get_edit_issue_meta': 'edit_issue_meta',
    'get_events': 'events',
    'get_failed_webhooks': 'failed_webhooks',
    'get_favourite_filters': 'favourite_filters',
    'get_features_for_project': 'features_for_project',
    'get_field_auto_complete_for_query_string': 'field_auto_complete_for_query_string',
    'get_field_configuration_items': 'field_configuration_items',
    'get_field_configuration_scheme_mappings': 'field_configuration_scheme_mappings',
    'get_field_configuration_scheme_project_mapping': 'field_configuration_scheme_project_mapping',
    'get_fields': 'fields',
    'get_fields_paginated': 'fields_paginated',
    'get_filter': 'filter',
    'get_filters': 'filters',
    'get_filters_paginated': 'filters_paginated',
    'get_group': 'group',
    'get_hierarchy': 'hierarchy',
    'get_ids_of_worklogs_deleted_since': 'ids_of_worklogs_deleted_since',
    'get_ids_of_worklogs_modified_since': 'ids_of_worklogs_modified_since',
    'get_is_watching_issue_bulk': 'is_watching_issue_bulk',
    'get_issue': 'issue',
    'get_issue_all_types': 'issue_all_types',
    'get_issue_field_option': 'issue_field_option',
    'get_issue_link': 'issue_link',
    'get_issue_link_type': 'issue_link_type',
    'get_issue_link_types': 'issue_link_types',
    'get_issue_navigator_default_columns': 'issue_navigator_default_columns',
    'get_issue_picker_resource': 'issue_picker_resource',
    'get_issue_property': 'issue_property',
    'get_issue_property_keys': 'issue_property_keys',
    'get_issue_security_level': 'issue_security_level',
    'get_issue_security_level_members': 'issue_security_level_members',
    'get_issue_security_scheme': 'issue_security_scheme',
    'get_issue_security_schemes': 'issue_security_schemes',
    'get_issue_type': 'issue_type',
    'get_issue_type_mappings_for_contexts': 'issue_type_mappings_for_contexts',
    'get_issue_type_property': 'issue_type_property',
    'get_issue_type_property_keys': 'issue_type_property_keys',
    'get_issue_type_scheme_for_projects': 'issue_type_scheme_for_projects',
    'get_issue_type_schemes_mapping': 'issue_type_schemes_mapping',
    'get_issue_type_screen_scheme_mappings': 'issue_type_screen_scheme_mappings',
    'get_issue_type_screen_scheme_project_associations': 'issue_type_screen_scheme_project_associations',
    'get_issue_type_screen_schemes': 'issue_type_screen_schemes',
    'get_issue_types_for_project': 'issue_types_for_project',
    'get_issue_watchers': 'issue_watchers',
    'get_issue_worklog': 'issue_worklog',
    'get_license': 'license',
    'get_locale': 'locale',
    'get_my_filters': 'my_filters',
    'get_my_permissions': 'my_permissions',
    'get_notification_scheme': 'notification_scheme',
    'get_notification_scheme_for_project': 'notification_scheme_for_project',
    'get_notification_scheme_to_project_mappings': 'notification_scheme_to_project_mappings',
    'get_notification_schemes': 'notification_schemes',
    'get_options_for_context': 'options_for_context',
    'get_permission_scheme': 'permission_scheme',
    'get_permission_scheme_grant': 'permission_scheme_grant',
    'get_permission_scheme_grants': 'permission_scheme_grants',
    'get_permitted_projects': 'permitted_projects',
    'get_precomputations': 'precomputations',
    'get_preference': 'preference',
    'get_priorities': 'priorities',
    'get_priority': 'priority',
    'get_project': 'project',
    'get_project_category_by_id': 'project_category_by_id',
    'get_project_components': 'project_components',
    'get_project_components_paginated': 'project_components_paginated',
    'get_project_context_mapping': 'project_context_mapping',
    'get_project_email': 'project_email',
    'get_project_issue_security_scheme': 'project_issue_security_scheme',
    'get_project_property': 'project_property',
    'get_project_property_keys': 'project_property_keys',
    'get_project_role': 'project_role',
    'get_project_role_actors_for_role': 'project_role_actors_for_role',
    'get_project_role_by_id': 'project_role_by_id',
    'get_project_role_details': 'project_role_details',
    'get_project_roles': 'project_roles',
    'get_project_type_by_key': 'project_type_by_key',
    'get_project_versions': 'project_versions',
    'get_project_versions_paginated': 'project_versions_paginated',
    'get_projects_for_issue_type_screen_scheme': 'projects_for_issue_type_screen_scheme',
    'get_recent': 'recent',
    'get_remote_issue_link_by_id': 'remote_issue_link_by_id',
    'get_remote_issue_links': 'remote_issue_links',
    'get_resolution': 'resolution',
    'get_resolutions': 'resolutions',
    'get_screen_schemes': 'screen_schemes',
    'get_screens': 'screens',
    'get_screens_for_field': 'screens_for_field',
    'get_security_levels_for_project': 'security_levels_for_project',
    'get_selectable_issue_field_options': 'selectable_issue_field_options',
    'get_selected_time_tracking_implementation': 'selected_time_tracking_implementation',
    'get_server_info': 'server_info',
    'get_share_permission': 'share_permission',
    'get_share_permissions': 'share_permissions',
    'get_shared_time_tracking_configuration': 'shared_time_tracking_configuration',
    'get_status': 'status',
    'get_status_categories': 'status_categories',
    'get_status_category': 'status_category',
    'get_statuses': 'statuses',
    'get_statuses_by_id': 'statuses_by_id',
    'get_task': 'task',
    'get_transitions': 'transitions',
    'get_trashed_fields_paginated': 'trashed_fields_paginated',
    'get_ui_modifications': 'ui_modifications',
    'get_user': 'user',
    'get_user_default_columns': 'user_default_columns',
    'get_user_email': 'user_email',
    'get_user_email_bulk': 'user_email_bulk',
    'get_user_groups': 'user_groups',
    'get_user_property': 'user_property',
    'get_user_property_keys': 'user_property_keys',
    'get_users_from_group': 'users_from_group',
    'get_valid_project_key': 'valid_project_key',
    'get_valid_project_name': 'valid_project_name',
    'get_version': 'version',
    'get_version_related_issues': 'version_related_issues',
    'get_version_unresolved_issues': 'version_unresolved_issues',
    'get_visible_issue_field_options': 'visible_issue_field_options',
    'get_votes': 'votes',
    'get_workflow': 'workflow',
    'get_workflow_scheme': 'workflow_scheme',
    'get_workflow_scheme_draft': 'workflow_scheme_draft',
    'get_workflow_scheme_draft_issue_type': 'workflow_scheme_draft_issue_type',
    'get_workflow_scheme_issue_type': 'workflow_scheme_issue_type',
    'get_workflow_scheme_project_associations': 'workflow_scheme_project_associations',
    'get_workflow_transition_properties': 'workflow_transition_properties',
    'get_workflow_transition_rule_configurations': 'workflow_transition_rule_configurations',
    'get_workflows_paginated': 'workflows_paginated',
    'get_worklog': 'worklog',
    'get_worklog_property': 'worklog_property',
    'get_worklog_property_keys': 'worklog_property_keys',
    'get_worklogs_for_ids': 'worklogs_for_ids',
    'link_issues': 'link',
    'match_issues': 'match',
    'merge_versions': 'merge',
    'migrate_queries': 'migrate',
    'migration_resource_update_entity_properties_value_put': 'migration_resource',
    'migration_resource_workflow_rule_search_post': 'migration_resource',
    'move_priorities': 'priorities',
    'move_resolutions': 'resolutions',
    'move_screen_tab': 'screen_tab',
    'move_screen_tab_field': 'screen_tab_field',
    'move_version': 'version',
    'notify': 'root',
    'parse_jql_queries': 'parse_jql',
    'partial_update_project_role': 'partial_update_project',
    'publish_draft_workflow_scheme': 'publish_draft_workflow',
    'refresh_webhooks': 'refresh',
    'register_dynamic_webhooks': 'register_dynamic',
    'remove_attachment': 'attachment',
    'remove_custom_field_context_from_projects': 'custom_field_context_from_projects',
    'remove_gadget': 'gadget',
    'remove_group': 'group',
    'remove_issue_type_from_issue_type_scheme': 'issue_type_from_issue_type_scheme',
    'remove_issue_types_from_context': 'issue_types_from_context',
    'remove_issue_types_from_global_field_configuration_scheme': 'issue_types_from_global_field_configuration_scheme',
    'remove_mappings_from_issue_type_screen_scheme': 'mappings_from_issue_type_screen_scheme',
    'remove_notification_from_notification_scheme': 'notification_from_notification_scheme',
    'remove_preference': 'preference',
    'remove_project_category': 'project_category',
    'remove_screen_tab_field': 'screen_tab_field',
    'remove_user': 'user',
    'remove_user_from_group': 'user_from_group',
    'remove_vote': 'vote',
    'remove_watcher': 'watcher',
    'rename_screen_tab': 'screen_tab',
    'reorder_custom_field_options': 'reorder_custom_field',
    'reorder_issue_types_in_issue_type_scheme': 'reorder_issue_types_in_issue_type',
    'replace_issue_field_option': 'replace_issue_field',
    'reset_columns': 'reset',
    'reset_user_columns': 'reset_user',
    'restore': 'root',
    'restore_custom_field': 'custom_field',
    'sanitise_jql_queries': 'sanitise_jql',
    'search': 'root',
    'search_for_issues_using_jql': 'for_issues_using_jql',
    'search_for_issues_using_jql_post': 'for_issues_using_jql_post',
    'search_priorities': 'priorities',
    'search_projects': 'projects',
    'search_resolutions': 'resolutions',
    'select_time_tracking_implementation': 'select_time_tracking',
    'set_actors': 'actors',
    'set_application_property': 'application_property',
    'set_banner': 'banner',
    'set_columns': 'columns',
    'set_comment_property': 'comment_property',
    'set_dashboard_item_property': 'dashboard_item_property',
    'set_default_priority': 'default_priority',
    'set_default_resolution': 'default_resolution',
    'set_default_share_scope': 'default_share_scope',
    'set_default_values': 'default_values',
    'set_favourite_for_filter': 'favourite_for_filter',
    'set_field_configuration_scheme_mapping': 'field_configuration_scheme_mapping',
    'set_issue_navigator_default_columns': 'issue_navigator_default_columns',
    'set_issue_property': 'issue_property',
    'set_issue_type_property': 'issue_type_property',
    'set_locale': 'locale',
    'set_preference': 'preference',
    'set_project_property': 'project_property',
    'set_shared_time_tracking_configuration': 'shared_time_tracking_configuration',
    'set_user_columns': 'user_columns',
    'set_user_property': 'user_property',
    'set_workflow_scheme_draft_issue_type': 'workflow_scheme_draft_issue_type',
    'set_workflow_scheme_issue_type': 'workflow_scheme_issue_type',
    'set_worklog_property': 'worklog_property',
    'store_avatar': 'store',
    'toggle_feature_for_project': 'toggle_feature_for',
    'trash_custom_field': 'custom_field',
    'update_comment': 'comment',
    'update_component': 'component',
    'update_custom_field': 'custom_field',
    'update_custom_field_configuration': 'custom_field_configuration',
    'update_custom_field_context': 'custom_field_context',
    'update_custom_field_option': 'custom_field_option',
    'update_custom_field_value': 'custom_field_value',
    'update_dashboard': 'dashboard',
    'update_default_screen_scheme': 'default_screen_scheme',
    'update_default_workflow': 'default_workflow',
    'update_draft_default_workflow': 'draft_default_workflow',
    'update_draft_workflow_mapping': 'draft_workflow_mapping',
    'update_field_configuration': 'field_configuration',
    'update_field_configuration_items': 'field_configuration_items',
    'update_field_configuration_scheme': 'field_configuration_scheme',
    'update_filter': 'filter',
    'update_gadget': 'gadget',
    'update_issue_field_option': 'issue_field_option',
    'update_issue_link_type': 'issue_link_type',
    'update_issue_type': 'issue_type',
    'update_issue_type_scheme': 'issue_type_scheme',
    'update_issue_type_screen_scheme': 'issue_type_screen_scheme',
    'update_multiple_custom_field_values': 'multiple_custom_field_values',
    'update_notification_scheme': 'notification_scheme',
    'update_permission_scheme': 'permission_scheme',
    'update_precomputations': 'precomputations',
    'update_priority': 'priority',
    'update_project': 'project',
    'update_project_avatar': 'project_avatar',
    'update_project_category': 'project_category',
    'update_project_email': 'project_email',
    'update_project_type': 'project_type',
    'update_remote_issue_link': 'remote_issue_link',
    'update_resolution': 'resolution',
    'update_screen': 'screen',
    'update_screen_scheme': 'screen_scheme',
    'update_statuses': 'statuses',
    'update_ui_modification': 'ui_modification',
    'update_version': 'version',
    'update_workflow_mapping': 'workflow_mapping',
    'update_workflow_scheme': 'workflow_scheme',
    'update_workflow_scheme_draft': 'workflow_scheme_draft',
    'update_workflow_transition_property': 'workflow_transition_property',
    'update_workflow_transition_rule_configurations': 'workflow_transition_rule_configurations',
    'update_worklog': 'worklog',
    'validate_project_key': 'validate_project',
}

RESOURCE_REGISTRY: dict[str, tuple[str, str]] = {
    'accessible_project_type_by_key': ('lemma_connectors.jira.resources.accessible_project_type_by_key', 'JiraAccessibleProjectTypeByKeyResource'),
    'actor': ('lemma_connectors.jira.resources.actor', 'JiraActorResource'),
    'actor_users': ('lemma_connectors.jira.resources.actor_users', 'JiraActorUsersResource'),
    'actors': ('lemma_connectors.jira.resources.actors', 'JiraActorsResource'),
    'addon_properties_resource': ('lemma_connectors.jira.resources.addon_properties_resource', 'JiraAddonPropertiesResourceResource'),
    'advanced_settings': ('lemma_connectors.jira.resources.advanced_settings', 'JiraAdvancedSettingsResource'),
    'all_accessible_project_types': ('lemma_connectors.jira.resources.all_accessible_project_types', 'JiraAllAccessibleProjectTypesResource'),
    'all_application_roles': ('lemma_connectors.jira.resources.all_application_roles', 'JiraAllApplicationRolesResource'),
    'all_available_dashboard_gadgets': ('lemma_connectors.jira.resources.all_available_dashboard_gadgets', 'JiraAllAvailableDashboardGadgetsResource'),
    'all_dashboards': ('lemma_connectors.jira.resources.all_dashboards', 'JiraAllDashboardsResource'),
    'all_field_configuration_schemes': ('lemma_connectors.jira.resources.all_field_configuration_schemes', 'JiraAllFieldConfigurationSchemesResource'),
    'all_field_configurations': ('lemma_connectors.jira.resources.all_field_configurations', 'JiraAllFieldConfigurationsResource'),
    'all_gadgets': ('lemma_connectors.jira.resources.all_gadgets', 'JiraAllGadgetsResource'),
    'all_issue_field_options': ('lemma_connectors.jira.resources.all_issue_field_options', 'JiraAllIssueFieldOptionsResource'),
    'all_issue_type_schemes': ('lemma_connectors.jira.resources.all_issue_type_schemes', 'JiraAllIssueTypeSchemesResource'),
    'all_labels': ('lemma_connectors.jira.resources.all_labels', 'JiraAllLabelsResource'),
    'all_permission_schemes': ('lemma_connectors.jira.resources.all_permission_schemes', 'JiraAllPermissionSchemesResource'),
    'all_permissions': ('lemma_connectors.jira.resources.all_permissions', 'JiraAllPermissionsResource'),
    'all_project_avatars': ('lemma_connectors.jira.resources.all_project_avatars', 'JiraAllProjectAvatarsResource'),
    'all_project_categories': ('lemma_connectors.jira.resources.all_project_categories', 'JiraAllProjectCategoriesResource'),
    'all_project_roles': ('lemma_connectors.jira.resources.all_project_roles', 'JiraAllProjectRolesResource'),
    'all_project_types': ('lemma_connectors.jira.resources.all_project_types', 'JiraAllProjectTypesResource'),
    'all_projects': ('lemma_connectors.jira.resources.all_projects', 'JiraAllProjectsResource'),
    'all_screen_tab_fields': ('lemma_connectors.jira.resources.all_screen_tab_fields', 'JiraAllScreenTabFieldsResource'),
    'all_screen_tabs': ('lemma_connectors.jira.resources.all_screen_tabs', 'JiraAllScreenTabsResource'),
    'all_statuses': ('lemma_connectors.jira.resources.all_statuses', 'JiraAllStatusesResource'),
    'all_system_avatars': ('lemma_connectors.jira.resources.all_system_avatars', 'JiraAllSystemAvatarsResource'),
    'all_users': ('lemma_connectors.jira.resources.all_users', 'JiraAllUsersResource'),
    'all_users_default': ('lemma_connectors.jira.resources.all_users_default', 'JiraAllUsersDefaultResource'),
    'all_workflow_schemes': ('lemma_connectors.jira.resources.all_workflow_schemes', 'JiraAllWorkflowSchemesResource'),
    'all_workflows': ('lemma_connectors.jira.resources.all_workflows', 'JiraAllWorkflowsResource'),
    'alternative_issue_types': ('lemma_connectors.jira.resources.alternative_issue_types', 'JiraAlternativeIssueTypesResource'),
    'analyse': ('lemma_connectors.jira.resources.analyse', 'JiraAnalyseResource'),
    'and_replace_version': ('lemma_connectors.jira.resources.and_replace_version', 'JiraAndReplaceVersionResource'),
    'app_issue_field_value_update_resource': ('lemma_connectors.jira.resources.app_issue_field_value_update_resource', 'JiraAppIssueFieldValueUpdateResourceResource'),
    'application_property': ('lemma_connectors.jira.resources.application_property', 'JiraApplicationPropertyResource'),
    'application_role': ('lemma_connectors.jira.resources.application_role', 'JiraApplicationRoleResource'),
    'approximate_application_license_count': ('lemma_connectors.jira.resources.approximate_application_license_count', 'JiraApproximateApplicationLicenseCountResource'),
    'approximate_license_count': ('lemma_connectors.jira.resources.approximate_license_count', 'JiraApproximateLicenseCountResource'),
    'assign': ('lemma_connectors.jira.resources.assign', 'JiraAssignResource'),
    'assign_field_configuration_scheme_to': ('lemma_connectors.jira.resources.assign_field_configuration_scheme_to', 'JiraAssignFieldConfigurationSchemeToResource'),
    'assign_issue_type_scheme_to': ('lemma_connectors.jira.resources.assign_issue_type_scheme_to', 'JiraAssignIssueTypeSchemeToResource'),
    'assign_issue_type_screen_scheme_to': ('lemma_connectors.jira.resources.assign_issue_type_screen_scheme_to', 'JiraAssignIssueTypeScreenSchemeToResource'),
    'assign_permission': ('lemma_connectors.jira.resources.assign_permission', 'JiraAssignPermissionResource'),
    'assign_projects_to_custom_field': ('lemma_connectors.jira.resources.assign_projects_to_custom_field', 'JiraAssignProjectsToCustomFieldResource'),
    'assign_scheme_to': ('lemma_connectors.jira.resources.assign_scheme_to', 'JiraAssignSchemeToResource'),
    'assigned_permission_scheme': ('lemma_connectors.jira.resources.assigned_permission_scheme', 'JiraAssignedPermissionSchemeResource'),
    'attachment': ('lemma_connectors.jira.resources.attachment', 'JiraAttachmentResource'),
    'attachment_content': ('lemma_connectors.jira.resources.attachment_content', 'JiraAttachmentContentResource'),
    'attachment_for_humans': ('lemma_connectors.jira.resources.attachment_for_humans', 'JiraAttachmentForHumansResource'),
    'attachment_for_machines': ('lemma_connectors.jira.resources.attachment_for_machines', 'JiraAttachmentForMachinesResource'),
    'attachment_meta': ('lemma_connectors.jira.resources.attachment_meta', 'JiraAttachmentMetaResource'),
    'attachment_thumbnail': ('lemma_connectors.jira.resources.attachment_thumbnail', 'JiraAttachmentThumbnailResource'),
    'audit_records': ('lemma_connectors.jira.resources.audit_records', 'JiraAuditRecordsResource'),
    'auto_complete': ('lemma_connectors.jira.resources.auto_complete', 'JiraAutoCompleteResource'),
    'auto_complete_post': ('lemma_connectors.jira.resources.auto_complete_post', 'JiraAutoCompletePostResource'),
    'available_screen_fields': ('lemma_connectors.jira.resources.available_screen_fields', 'JiraAvailableScreenFieldsResource'),
    'available_time_tracking_implementations': ('lemma_connectors.jira.resources.available_time_tracking_implementations', 'JiraAvailableTimeTrackingImplementationsResource'),
    'avatar': ('lemma_connectors.jira.resources.avatar', 'JiraAvatarResource'),
    'avatar_image_by_id': ('lemma_connectors.jira.resources.avatar_image_by_id', 'JiraAvatarImageByIdResource'),
    'avatar_image_by_owner': ('lemma_connectors.jira.resources.avatar_image_by_owner', 'JiraAvatarImageByOwnerResource'),
    'avatar_image_by_type': ('lemma_connectors.jira.resources.avatar_image_by_type', 'JiraAvatarImageByTypeResource'),
    'avatars': ('lemma_connectors.jira.resources.avatars', 'JiraAvatarsResource'),
    'banner': ('lemma_connectors.jira.resources.banner', 'JiraBannerResource'),
    'bulk_delete_issue': ('lemma_connectors.jira.resources.bulk_delete_issue', 'JiraBulkDeleteIssueResource'),
    'bulk_get': ('lemma_connectors.jira.resources.bulk_get', 'JiraBulkGetResource'),
    'bulk_get_users': ('lemma_connectors.jira.resources.bulk_get_users', 'JiraBulkGetUsersResource'),
    'bulk_permissions': ('lemma_connectors.jira.resources.bulk_permissions', 'JiraBulkPermissionsResource'),
    'bulk_set_issue': ('lemma_connectors.jira.resources.bulk_set_issue', 'JiraBulkSetIssueResource'),
    'bulk_set_issue_properties_by': ('lemma_connectors.jira.resources.bulk_set_issue_properties_by', 'JiraBulkSetIssuePropertiesByResource'),
    'bulk_set_issues_properties': ('lemma_connectors.jira.resources.bulk_set_issues_properties', 'JiraBulkSetIssuesPropertiesResource'),
    'cancel': ('lemma_connectors.jira.resources.cancel', 'JiraCancelResource'),
    'change_filter': ('lemma_connectors.jira.resources.change_filter', 'JiraChangeFilterResource'),
    'change_logs': ('lemma_connectors.jira.resources.change_logs', 'JiraChangeLogsResource'),
    'change_logs_by_ids': ('lemma_connectors.jira.resources.change_logs_by_ids', 'JiraChangeLogsByIdsResource'),
    'columns': ('lemma_connectors.jira.resources.columns', 'JiraColumnsResource'),
    'comment': ('lemma_connectors.jira.resources.comment', 'JiraCommentResource'),
    'comment_property': ('lemma_connectors.jira.resources.comment_property', 'JiraCommentPropertyResource'),
    'comment_property_keys': ('lemma_connectors.jira.resources.comment_property_keys', 'JiraCommentPropertyKeysResource'),
    'comments': ('lemma_connectors.jira.resources.comments', 'JiraCommentsResource'),
    'comments_by_ids': ('lemma_connectors.jira.resources.comments_by_ids', 'JiraCommentsByIdsResource'),
    'component': ('lemma_connectors.jira.resources.component', 'JiraComponentResource'),
    'component_related_issues': ('lemma_connectors.jira.resources.component_related_issues', 'JiraComponentRelatedIssuesResource'),
    'configuration': ('lemma_connectors.jira.resources.configuration', 'JiraConfigurationResource'),
    'contexts_for_field': ('lemma_connectors.jira.resources.contexts_for_field', 'JiraContextsForFieldResource'),
    'contexts_for_field_deprecated': ('lemma_connectors.jira.resources.contexts_for_field_deprecated', 'JiraContextsForFieldDeprecatedResource'),
    'create_issue_meta': ('lemma_connectors.jira.resources.create_issue_meta', 'JiraCreateIssueMetaResource'),
    'current_user': ('lemma_connectors.jira.resources.current_user', 'JiraCurrentUserResource'),
    'custom_field': ('lemma_connectors.jira.resources.custom_field', 'JiraCustomFieldResource'),
    'custom_field_configuration': ('lemma_connectors.jira.resources.custom_field_configuration', 'JiraCustomFieldConfigurationResource'),
    'custom_field_context': ('lemma_connectors.jira.resources.custom_field_context', 'JiraCustomFieldContextResource'),
    'custom_field_context_from_projects': ('lemma_connectors.jira.resources.custom_field_context_from_projects', 'JiraCustomFieldContextFromProjectsResource'),
    'custom_field_contexts_for_projects_and_issue_types': ('lemma_connectors.jira.resources.custom_field_contexts_for_projects_and_issue_types', 'JiraCustomFieldContextsForProjectsAndIssueTypesResource'),
    'custom_field_option': ('lemma_connectors.jira.resources.custom_field_option', 'JiraCustomFieldOptionResource'),
    'custom_field_value': ('lemma_connectors.jira.resources.custom_field_value', 'JiraCustomFieldValueResource'),
    'dashboard': ('lemma_connectors.jira.resources.dashboard', 'JiraDashboardResource'),
    'dashboard_item_property': ('lemma_connectors.jira.resources.dashboard_item_property', 'JiraDashboardItemPropertyResource'),
    'dashboard_item_property_keys': ('lemma_connectors.jira.resources.dashboard_item_property_keys', 'JiraDashboardItemPropertyKeysResource'),
    'dashboards_paginated': ('lemma_connectors.jira.resources.dashboards_paginated', 'JiraDashboardsPaginatedResource'),
    'default_priority': ('lemma_connectors.jira.resources.default_priority', 'JiraDefaultPriorityResource'),
    'default_resolution': ('lemma_connectors.jira.resources.default_resolution', 'JiraDefaultResolutionResource'),
    'default_screen_scheme': ('lemma_connectors.jira.resources.default_screen_scheme', 'JiraDefaultScreenSchemeResource'),
    'default_share_scope': ('lemma_connectors.jira.resources.default_share_scope', 'JiraDefaultShareScopeResource'),
    'default_values': ('lemma_connectors.jira.resources.default_values', 'JiraDefaultValuesResource'),
    'default_workflow': ('lemma_connectors.jira.resources.default_workflow', 'JiraDefaultWorkflowResource'),
    'do': ('lemma_connectors.jira.resources.do', 'JiraDoResource'),
    'draft_default_workflow': ('lemma_connectors.jira.resources.draft_default_workflow', 'JiraDraftDefaultWorkflowResource'),
    'draft_workflow': ('lemma_connectors.jira.resources.draft_workflow', 'JiraDraftWorkflowResource'),
    'draft_workflow_mapping': ('lemma_connectors.jira.resources.draft_workflow_mapping', 'JiraDraftWorkflowMappingResource'),
    'dynamic_modules_resource': ('lemma_connectors.jira.resources.dynamic_modules_resource', 'JiraDynamicModulesResourceResource'),
    'dynamic_webhooks_for_app': ('lemma_connectors.jira.resources.dynamic_webhooks_for_app', 'JiraDynamicWebhooksForAppResource'),
    'edit': ('lemma_connectors.jira.resources.edit', 'JiraEditResource'),
    'edit_issue_meta': ('lemma_connectors.jira.resources.edit_issue_meta', 'JiraEditIssueMetaResource'),
    'evaluate_jira': ('lemma_connectors.jira.resources.evaluate_jira', 'JiraEvaluateJiraResource'),
    'events': ('lemma_connectors.jira.resources.events', 'JiraEventsResource'),
    'failed_webhooks': ('lemma_connectors.jira.resources.failed_webhooks', 'JiraFailedWebhooksResource'),
    'favourite_filters': ('lemma_connectors.jira.resources.favourite_filters', 'JiraFavouriteFiltersResource'),
    'favourite_for_filter': ('lemma_connectors.jira.resources.favourite_for_filter', 'JiraFavouriteForFilterResource'),
    'features_for_project': ('lemma_connectors.jira.resources.features_for_project', 'JiraFeaturesForProjectResource'),
    'field_auto_complete_for_query_string': ('lemma_connectors.jira.resources.field_auto_complete_for_query_string', 'JiraFieldAutoCompleteForQueryStringResource'),
    'field_configuration': ('lemma_connectors.jira.resources.field_configuration', 'JiraFieldConfigurationResource'),
    'field_configuration_items': ('lemma_connectors.jira.resources.field_configuration_items', 'JiraFieldConfigurationItemsResource'),
    'field_configuration_scheme': ('lemma_connectors.jira.resources.field_configuration_scheme', 'JiraFieldConfigurationSchemeResource'),
    'field_configuration_scheme_mapping': ('lemma_connectors.jira.resources.field_configuration_scheme_mapping', 'JiraFieldConfigurationSchemeMappingResource'),
    'field_configuration_scheme_mappings': ('lemma_connectors.jira.resources.field_configuration_scheme_mappings', 'JiraFieldConfigurationSchemeMappingsResource'),
    'field_configuration_scheme_project_mapping': ('lemma_connectors.jira.resources.field_configuration_scheme_project_mapping', 'JiraFieldConfigurationSchemeProjectMappingResource'),
    'field_to_default_screen': ('lemma_connectors.jira.resources.field_to_default_screen', 'JiraFieldToDefaultScreenResource'),
    'fields': ('lemma_connectors.jira.resources.fields', 'JiraFieldsResource'),
    'fields_paginated': ('lemma_connectors.jira.resources.fields_paginated', 'JiraFieldsPaginatedResource'),
    'filter': ('lemma_connectors.jira.resources.filter', 'JiraFilterResource'),
    'filters': ('lemma_connectors.jira.resources.filters', 'JiraFiltersResource'),
    'filters_paginated': ('lemma_connectors.jira.resources.filters_paginated', 'JiraFiltersPaginatedResource'),
    'find': ('lemma_connectors.jira.resources.find', 'JiraFindResource'),
    'find_assignable': ('lemma_connectors.jira.resources.find_assignable', 'JiraFindAssignableResource'),
    'find_bulk_assignable': ('lemma_connectors.jira.resources.find_bulk_assignable', 'JiraFindBulkAssignableResource'),
    'find_user_keys_by': ('lemma_connectors.jira.resources.find_user_keys_by', 'JiraFindUserKeysByResource'),
    'find_users_and': ('lemma_connectors.jira.resources.find_users_and', 'JiraFindUsersAndResource'),
    'find_users_by': ('lemma_connectors.jira.resources.find_users_by', 'JiraFindUsersByResource'),
    'find_users_for': ('lemma_connectors.jira.resources.find_users_for', 'JiraFindUsersForResource'),
    'find_users_with_all': ('lemma_connectors.jira.resources.find_users_with_all', 'JiraFindUsersWithAllResource'),
    'find_users_with_browse': ('lemma_connectors.jira.resources.find_users_with_browse', 'JiraFindUsersWithBrowseResource'),
    'for_issues_using_jql': ('lemma_connectors.jira.resources.for_issues_using_jql', 'JiraForIssuesUsingJqlResource'),
    'for_issues_using_jql_post': ('lemma_connectors.jira.resources.for_issues_using_jql_post', 'JiraForIssuesUsingJqlPostResource'),
    'fully_update_project': ('lemma_connectors.jira.resources.fully_update_project', 'JiraFullyUpdateProjectResource'),
    'gadget': ('lemma_connectors.jira.resources.gadget', 'JiraGadgetResource'),
    'group': ('lemma_connectors.jira.resources.group', 'JiraGroupResource'),
    'hierarchy': ('lemma_connectors.jira.resources.hierarchy', 'JiraHierarchyResource'),
    'ids_of_worklogs_deleted_since': ('lemma_connectors.jira.resources.ids_of_worklogs_deleted_since', 'JiraIdsOfWorklogsDeletedSinceResource'),
    'ids_of_worklogs_modified_since': ('lemma_connectors.jira.resources.ids_of_worklogs_modified_since', 'JiraIdsOfWorklogsModifiedSinceResource'),
    'inactive_workflow': ('lemma_connectors.jira.resources.inactive_workflow', 'JiraInactiveWorkflowResource'),
    'is_watching_issue_bulk': ('lemma_connectors.jira.resources.is_watching_issue_bulk', 'JiraIsWatchingIssueBulkResource'),
    'issue': ('lemma_connectors.jira.resources.issue', 'JiraIssueResource'),
    'issue_all_types': ('lemma_connectors.jira.resources.issue_all_types', 'JiraIssueAllTypesResource'),
    'issue_field_option': ('lemma_connectors.jira.resources.issue_field_option', 'JiraIssueFieldOptionResource'),
    'issue_link': ('lemma_connectors.jira.resources.issue_link', 'JiraIssueLinkResource'),
    'issue_link_type': ('lemma_connectors.jira.resources.issue_link_type', 'JiraIssueLinkTypeResource'),
    'issue_link_types': ('lemma_connectors.jira.resources.issue_link_types', 'JiraIssueLinkTypesResource'),
    'issue_navigator_default_columns': ('lemma_connectors.jira.resources.issue_navigator_default_columns', 'JiraIssueNavigatorDefaultColumnsResource'),
    'issue_picker_resource': ('lemma_connectors.jira.resources.issue_picker_resource', 'JiraIssuePickerResourceResource'),
    'issue_property': ('lemma_connectors.jira.resources.issue_property', 'JiraIssuePropertyResource'),
    'issue_property_keys': ('lemma_connectors.jira.resources.issue_property_keys', 'JiraIssuePropertyKeysResource'),
    'issue_security_level': ('lemma_connectors.jira.resources.issue_security_level', 'JiraIssueSecurityLevelResource'),
    'issue_security_level_members': ('lemma_connectors.jira.resources.issue_security_level_members', 'JiraIssueSecurityLevelMembersResource'),
    'issue_security_scheme': ('lemma_connectors.jira.resources.issue_security_scheme', 'JiraIssueSecuritySchemeResource'),
    'issue_security_schemes': ('lemma_connectors.jira.resources.issue_security_schemes', 'JiraIssueSecuritySchemesResource'),
    'issue_type': ('lemma_connectors.jira.resources.issue_type', 'JiraIssueTypeResource'),
    'issue_type_avatar': ('lemma_connectors.jira.resources.issue_type_avatar', 'JiraIssueTypeAvatarResource'),
    'issue_type_from_issue_type_scheme': ('lemma_connectors.jira.resources.issue_type_from_issue_type_scheme', 'JiraIssueTypeFromIssueTypeSchemeResource'),
    'issue_type_mappings_for_contexts': ('lemma_connectors.jira.resources.issue_type_mappings_for_contexts', 'JiraIssueTypeMappingsForContextsResource'),
    'issue_type_property': ('lemma_connectors.jira.resources.issue_type_property', 'JiraIssueTypePropertyResource'),
    'issue_type_property_keys': ('lemma_connectors.jira.resources.issue_type_property_keys', 'JiraIssueTypePropertyKeysResource'),
    'issue_type_scheme': ('lemma_connectors.jira.resources.issue_type_scheme', 'JiraIssueTypeSchemeResource'),
    'issue_type_scheme_for_projects': ('lemma_connectors.jira.resources.issue_type_scheme_for_projects', 'JiraIssueTypeSchemeForProjectsResource'),
    'issue_type_schemes_mapping': ('lemma_connectors.jira.resources.issue_type_schemes_mapping', 'JiraIssueTypeSchemesMappingResource'),
    'issue_type_screen_scheme': ('lemma_connectors.jira.resources.issue_type_screen_scheme', 'JiraIssueTypeScreenSchemeResource'),
    'issue_type_screen_scheme_mappings': ('lemma_connectors.jira.resources.issue_type_screen_scheme_mappings', 'JiraIssueTypeScreenSchemeMappingsResource'),
    'issue_type_screen_scheme_project_associations': ('lemma_connectors.jira.resources.issue_type_screen_scheme_project_associations', 'JiraIssueTypeScreenSchemeProjectAssociationsResource'),
    'issue_type_screen_schemes': ('lemma_connectors.jira.resources.issue_type_screen_schemes', 'JiraIssueTypeScreenSchemesResource'),
    'issue_types_for_project': ('lemma_connectors.jira.resources.issue_types_for_project', 'JiraIssueTypesForProjectResource'),
    'issue_types_from_context': ('lemma_connectors.jira.resources.issue_types_from_context', 'JiraIssueTypesFromContextResource'),
    'issue_types_from_global_field_configuration_scheme': ('lemma_connectors.jira.resources.issue_types_from_global_field_configuration_scheme', 'JiraIssueTypesFromGlobalFieldConfigurationSchemeResource'),
    'issue_types_to_context': ('lemma_connectors.jira.resources.issue_types_to_context', 'JiraIssueTypesToContextResource'),
    'issue_types_to_issue_type_scheme': ('lemma_connectors.jira.resources.issue_types_to_issue_type_scheme', 'JiraIssueTypesToIssueTypeSchemeResource'),
    'issue_watchers': ('lemma_connectors.jira.resources.issue_watchers', 'JiraIssueWatchersResource'),
    'issue_worklog': ('lemma_connectors.jira.resources.issue_worklog', 'JiraIssueWorklogResource'),
    'issues': ('lemma_connectors.jira.resources.issues', 'JiraIssuesResource'),
    'license': ('lemma_connectors.jira.resources.license', 'JiraLicenseResource'),
    'link': ('lemma_connectors.jira.resources.link', 'JiraLinkResource'),
    'locale': ('lemma_connectors.jira.resources.locale', 'JiraLocaleResource'),
    'mappings_for_issue_type_screen_scheme': ('lemma_connectors.jira.resources.mappings_for_issue_type_screen_scheme', 'JiraMappingsForIssueTypeScreenSchemeResource'),
    'mappings_from_issue_type_screen_scheme': ('lemma_connectors.jira.resources.mappings_from_issue_type_screen_scheme', 'JiraMappingsFromIssueTypeScreenSchemeResource'),
    'match': ('lemma_connectors.jira.resources.match', 'JiraMatchResource'),
    'merge': ('lemma_connectors.jira.resources.merge', 'JiraMergeResource'),
    'migrate': ('lemma_connectors.jira.resources.migrate', 'JiraMigrateResource'),
    'migration_resource': ('lemma_connectors.jira.resources.migration_resource', 'JiraMigrationResourceResource'),
    'multiple_custom_field_values': ('lemma_connectors.jira.resources.multiple_custom_field_values', 'JiraMultipleCustomFieldValuesResource'),
    'my_filters': ('lemma_connectors.jira.resources.my_filters', 'JiraMyFiltersResource'),
    'my_permissions': ('lemma_connectors.jira.resources.my_permissions', 'JiraMyPermissionsResource'),
    'notification_from_notification_scheme': ('lemma_connectors.jira.resources.notification_from_notification_scheme', 'JiraNotificationFromNotificationSchemeResource'),
    'notification_scheme': ('lemma_connectors.jira.resources.notification_scheme', 'JiraNotificationSchemeResource'),
    'notification_scheme_for_project': ('lemma_connectors.jira.resources.notification_scheme_for_project', 'JiraNotificationSchemeForProjectResource'),
    'notification_scheme_to_project_mappings': ('lemma_connectors.jira.resources.notification_scheme_to_project_mappings', 'JiraNotificationSchemeToProjectMappingsResource'),
    'notification_schemes': ('lemma_connectors.jira.resources.notification_schemes', 'JiraNotificationSchemesResource'),
    'notifications': ('lemma_connectors.jira.resources.notifications', 'JiraNotificationsResource'),
    'options_for_context': ('lemma_connectors.jira.resources.options_for_context', 'JiraOptionsForContextResource'),
    'or_update_remote_issue_link': ('lemma_connectors.jira.resources.or_update_remote_issue_link', 'JiraOrUpdateRemoteIssueLinkResource'),
    'parse_jql': ('lemma_connectors.jira.resources.parse_jql', 'JiraParseJqlResource'),
    'partial_update_project': ('lemma_connectors.jira.resources.partial_update_project', 'JiraPartialUpdateProjectResource'),
    'permission_grant': ('lemma_connectors.jira.resources.permission_grant', 'JiraPermissionGrantResource'),
    'permission_scheme': ('lemma_connectors.jira.resources.permission_scheme', 'JiraPermissionSchemeResource'),
    'permission_scheme_entity': ('lemma_connectors.jira.resources.permission_scheme_entity', 'JiraPermissionSchemeEntityResource'),
    'permission_scheme_grant': ('lemma_connectors.jira.resources.permission_scheme_grant', 'JiraPermissionSchemeGrantResource'),
    'permission_scheme_grants': ('lemma_connectors.jira.resources.permission_scheme_grants', 'JiraPermissionSchemeGrantsResource'),
    'permitted_projects': ('lemma_connectors.jira.resources.permitted_projects', 'JiraPermittedProjectsResource'),
    'precomputations': ('lemma_connectors.jira.resources.precomputations', 'JiraPrecomputationsResource'),
    'preference': ('lemma_connectors.jira.resources.preference', 'JiraPreferenceResource'),
    'priorities': ('lemma_connectors.jira.resources.priorities', 'JiraPrioritiesResource'),
    'priority': ('lemma_connectors.jira.resources.priority', 'JiraPriorityResource'),
    'project': ('lemma_connectors.jira.resources.project', 'JiraProjectResource'),
    'project_asynchronously': ('lemma_connectors.jira.resources.project_asynchronously', 'JiraProjectAsynchronouslyResource'),
    'project_avatar': ('lemma_connectors.jira.resources.project_avatar', 'JiraProjectAvatarResource'),
    'project_category': ('lemma_connectors.jira.resources.project_category', 'JiraProjectCategoryResource'),
    'project_category_by_id': ('lemma_connectors.jira.resources.project_category_by_id', 'JiraProjectCategoryByIdResource'),
    'project_components': ('lemma_connectors.jira.resources.project_components', 'JiraProjectComponentsResource'),
    'project_components_paginated': ('lemma_connectors.jira.resources.project_components_paginated', 'JiraProjectComponentsPaginatedResource'),
    'project_context_mapping': ('lemma_connectors.jira.resources.project_context_mapping', 'JiraProjectContextMappingResource'),
    'project_email': ('lemma_connectors.jira.resources.project_email', 'JiraProjectEmailResource'),
    'project_issue_security_scheme': ('lemma_connectors.jira.resources.project_issue_security_scheme', 'JiraProjectIssueSecuritySchemeResource'),
    'project_property': ('lemma_connectors.jira.resources.project_property', 'JiraProjectPropertyResource'),
    'project_property_keys': ('lemma_connectors.jira.resources.project_property_keys', 'JiraProjectPropertyKeysResource'),
    'project_role': ('lemma_connectors.jira.resources.project_role', 'JiraProjectRoleResource'),
    'project_role_actors_for_role': ('lemma_connectors.jira.resources.project_role_actors_for_role', 'JiraProjectRoleActorsForRoleResource'),
    'project_role_actors_from_role': ('lemma_connectors.jira.resources.project_role_actors_from_role', 'JiraProjectRoleActorsFromRoleResource'),
    'project_role_actors_to_role': ('lemma_connectors.jira.resources.project_role_actors_to_role', 'JiraProjectRoleActorsToRoleResource'),
    'project_role_by_id': ('lemma_connectors.jira.resources.project_role_by_id', 'JiraProjectRoleByIdResource'),
    'project_role_details': ('lemma_connectors.jira.resources.project_role_details', 'JiraProjectRoleDetailsResource'),
    'project_roles': ('lemma_connectors.jira.resources.project_roles', 'JiraProjectRolesResource'),
    'project_type': ('lemma_connectors.jira.resources.project_type', 'JiraProjectTypeResource'),
    'project_type_by_key': ('lemma_connectors.jira.resources.project_type_by_key', 'JiraProjectTypeByKeyResource'),
    'project_versions': ('lemma_connectors.jira.resources.project_versions', 'JiraProjectVersionsResource'),
    'project_versions_paginated': ('lemma_connectors.jira.resources.project_versions_paginated', 'JiraProjectVersionsPaginatedResource'),
    'projects': ('lemma_connectors.jira.resources.projects', 'JiraProjectsResource'),
    'projects_for_issue_type_screen_scheme': ('lemma_connectors.jira.resources.projects_for_issue_type_screen_scheme', 'JiraProjectsForIssueTypeScreenSchemeResource'),
    'publish_draft_workflow': ('lemma_connectors.jira.resources.publish_draft_workflow', 'JiraPublishDraftWorkflowResource'),
    'recent': ('lemma_connectors.jira.resources.recent', 'JiraRecentResource'),
    'refresh': ('lemma_connectors.jira.resources.refresh', 'JiraRefreshResource'),
    'register_dynamic': ('lemma_connectors.jira.resources.register_dynamic', 'JiraRegisterDynamicResource'),
    'remote_issue_link': ('lemma_connectors.jira.resources.remote_issue_link', 'JiraRemoteIssueLinkResource'),
    'remote_issue_link_by_global_id': ('lemma_connectors.jira.resources.remote_issue_link_by_global_id', 'JiraRemoteIssueLinkByGlobalIdResource'),
    'remote_issue_link_by_id': ('lemma_connectors.jira.resources.remote_issue_link_by_id', 'JiraRemoteIssueLinkByIdResource'),
    'remote_issue_links': ('lemma_connectors.jira.resources.remote_issue_links', 'JiraRemoteIssueLinksResource'),
    'reorder_custom_field': ('lemma_connectors.jira.resources.reorder_custom_field', 'JiraReorderCustomFieldResource'),
    'reorder_issue_types_in_issue_type': ('lemma_connectors.jira.resources.reorder_issue_types_in_issue_type', 'JiraReorderIssueTypesInIssueTypeResource'),
    'replace_issue_field': ('lemma_connectors.jira.resources.replace_issue_field', 'JiraReplaceIssueFieldResource'),
    'reset': ('lemma_connectors.jira.resources.reset', 'JiraResetResource'),
    'reset_user': ('lemma_connectors.jira.resources.reset_user', 'JiraResetUserResource'),
    'resolution': ('lemma_connectors.jira.resources.resolution', 'JiraResolutionResource'),
    'resolutions': ('lemma_connectors.jira.resources.resolutions', 'JiraResolutionsResource'),
    'root': ('lemma_connectors.jira.resources.root', 'JiraRootResource'),
    'sanitise_jql': ('lemma_connectors.jira.resources.sanitise_jql', 'JiraSanitiseJqlResource'),
    'screen': ('lemma_connectors.jira.resources.screen', 'JiraScreenResource'),
    'screen_scheme': ('lemma_connectors.jira.resources.screen_scheme', 'JiraScreenSchemeResource'),
    'screen_schemes': ('lemma_connectors.jira.resources.screen_schemes', 'JiraScreenSchemesResource'),
    'screen_tab': ('lemma_connectors.jira.resources.screen_tab', 'JiraScreenTabResource'),
    'screen_tab_field': ('lemma_connectors.jira.resources.screen_tab_field', 'JiraScreenTabFieldResource'),
    'screens': ('lemma_connectors.jira.resources.screens', 'JiraScreensResource'),
    'screens_for_field': ('lemma_connectors.jira.resources.screens_for_field', 'JiraScreensForFieldResource'),
    'security_levels_for_project': ('lemma_connectors.jira.resources.security_levels_for_project', 'JiraSecurityLevelsForProjectResource'),
    'select_time_tracking': ('lemma_connectors.jira.resources.select_time_tracking', 'JiraSelectTimeTrackingResource'),
    'selectable_issue_field_options': ('lemma_connectors.jira.resources.selectable_issue_field_options', 'JiraSelectableIssueFieldOptionsResource'),
    'selected_time_tracking_implementation': ('lemma_connectors.jira.resources.selected_time_tracking_implementation', 'JiraSelectedTimeTrackingImplementationResource'),
    'server_info': ('lemma_connectors.jira.resources.server_info', 'JiraServerInfoResource'),
    'share_permission': ('lemma_connectors.jira.resources.share_permission', 'JiraSharePermissionResource'),
    'share_permissions': ('lemma_connectors.jira.resources.share_permissions', 'JiraSharePermissionsResource'),
    'shared_time_tracking_configuration': ('lemma_connectors.jira.resources.shared_time_tracking_configuration', 'JiraSharedTimeTrackingConfigurationResource'),
    'status': ('lemma_connectors.jira.resources.status', 'JiraStatusResource'),
    'status_categories': ('lemma_connectors.jira.resources.status_categories', 'JiraStatusCategoriesResource'),
    'status_category': ('lemma_connectors.jira.resources.status_category', 'JiraStatusCategoryResource'),
    'statuses': ('lemma_connectors.jira.resources.statuses', 'JiraStatusesResource'),
    'statuses_by_id': ('lemma_connectors.jira.resources.statuses_by_id', 'JiraStatusesByIdResource'),
    'store': ('lemma_connectors.jira.resources.store', 'JiraStoreResource'),
    'task': ('lemma_connectors.jira.resources.task', 'JiraTaskResource'),
    'toggle_feature_for': ('lemma_connectors.jira.resources.toggle_feature_for', 'JiraToggleFeatureForResource'),
    'transitions': ('lemma_connectors.jira.resources.transitions', 'JiraTransitionsResource'),
    'trashed_fields_paginated': ('lemma_connectors.jira.resources.trashed_fields_paginated', 'JiraTrashedFieldsPaginatedResource'),
    'ui_modification': ('lemma_connectors.jira.resources.ui_modification', 'JiraUiModificationResource'),
    'ui_modifications': ('lemma_connectors.jira.resources.ui_modifications', 'JiraUiModificationsResource'),
    'user': ('lemma_connectors.jira.resources.user', 'JiraUserResource'),
    'user_columns': ('lemma_connectors.jira.resources.user_columns', 'JiraUserColumnsResource'),
    'user_default_columns': ('lemma_connectors.jira.resources.user_default_columns', 'JiraUserDefaultColumnsResource'),
    'user_email': ('lemma_connectors.jira.resources.user_email', 'JiraUserEmailResource'),
    'user_email_bulk': ('lemma_connectors.jira.resources.user_email_bulk', 'JiraUserEmailBulkResource'),
    'user_from_group': ('lemma_connectors.jira.resources.user_from_group', 'JiraUserFromGroupResource'),
    'user_groups': ('lemma_connectors.jira.resources.user_groups', 'JiraUserGroupsResource'),
    'user_property': ('lemma_connectors.jira.resources.user_property', 'JiraUserPropertyResource'),
    'user_property_keys': ('lemma_connectors.jira.resources.user_property_keys', 'JiraUserPropertyKeysResource'),
    'user_to_group': ('lemma_connectors.jira.resources.user_to_group', 'JiraUserToGroupResource'),
    'users_from_group': ('lemma_connectors.jira.resources.users_from_group', 'JiraUsersFromGroupResource'),
    'valid_project_key': ('lemma_connectors.jira.resources.valid_project_key', 'JiraValidProjectKeyResource'),
    'valid_project_name': ('lemma_connectors.jira.resources.valid_project_name', 'JiraValidProjectNameResource'),
    'validate_project': ('lemma_connectors.jira.resources.validate_project', 'JiraValidateProjectResource'),
    'version': ('lemma_connectors.jira.resources.version', 'JiraVersionResource'),
    'version_related_issues': ('lemma_connectors.jira.resources.version_related_issues', 'JiraVersionRelatedIssuesResource'),
    'version_unresolved_issues': ('lemma_connectors.jira.resources.version_unresolved_issues', 'JiraVersionUnresolvedIssuesResource'),
    'visible_issue_field_options': ('lemma_connectors.jira.resources.visible_issue_field_options', 'JiraVisibleIssueFieldOptionsResource'),
    'vote': ('lemma_connectors.jira.resources.vote', 'JiraVoteResource'),
    'votes': ('lemma_connectors.jira.resources.votes', 'JiraVotesResource'),
    'watcher': ('lemma_connectors.jira.resources.watcher', 'JiraWatcherResource'),
    'webhook_by_id': ('lemma_connectors.jira.resources.webhook_by_id', 'JiraWebhookByIdResource'),
    'workflow': ('lemma_connectors.jira.resources.workflow', 'JiraWorkflowResource'),
    'workflow_mapping': ('lemma_connectors.jira.resources.workflow_mapping', 'JiraWorkflowMappingResource'),
    'workflow_scheme': ('lemma_connectors.jira.resources.workflow_scheme', 'JiraWorkflowSchemeResource'),
    'workflow_scheme_draft': ('lemma_connectors.jira.resources.workflow_scheme_draft', 'JiraWorkflowSchemeDraftResource'),
    'workflow_scheme_draft_from_parent': ('lemma_connectors.jira.resources.workflow_scheme_draft_from_parent', 'JiraWorkflowSchemeDraftFromParentResource'),
    'workflow_scheme_draft_issue_type': ('lemma_connectors.jira.resources.workflow_scheme_draft_issue_type', 'JiraWorkflowSchemeDraftIssueTypeResource'),
    'workflow_scheme_issue_type': ('lemma_connectors.jira.resources.workflow_scheme_issue_type', 'JiraWorkflowSchemeIssueTypeResource'),
    'workflow_scheme_project_associations': ('lemma_connectors.jira.resources.workflow_scheme_project_associations', 'JiraWorkflowSchemeProjectAssociationsResource'),
    'workflow_transition_properties': ('lemma_connectors.jira.resources.workflow_transition_properties', 'JiraWorkflowTransitionPropertiesResource'),
    'workflow_transition_property': ('lemma_connectors.jira.resources.workflow_transition_property', 'JiraWorkflowTransitionPropertyResource'),
    'workflow_transition_rule_configurations': ('lemma_connectors.jira.resources.workflow_transition_rule_configurations', 'JiraWorkflowTransitionRuleConfigurationsResource'),
    'workflows_paginated': ('lemma_connectors.jira.resources.workflows_paginated', 'JiraWorkflowsPaginatedResource'),
    'worklog': ('lemma_connectors.jira.resources.worklog', 'JiraWorklogResource'),
    'worklog_property': ('lemma_connectors.jira.resources.worklog_property', 'JiraWorklogPropertyResource'),
    'worklog_property_keys': ('lemma_connectors.jira.resources.worklog_property_keys', 'JiraWorklogPropertyKeysResource'),
    'worklogs_for_ids': ('lemma_connectors.jira.resources.worklogs_for_ids', 'JiraWorklogsForIdsResource'),
}


def build_resource(client, resource_slug: str):
    """Lazily import and build a single resource client by slug."""
    module_path, class_name = RESOURCE_REGISTRY[resource_slug]
    module = importlib.import_module(module_path)
    return getattr(module, class_name)(client)


def build_resources(client):
    """Eagerly build all resource clients (backward-compatible)."""
    return {slug: build_resource(client, slug) for slug in RESOURCE_REGISTRY}
